theme: jekyll-theme-minimal

baseurl: ""

author: Anna

title: Coffee Medicine Science
description: Some site for a weirdo

github:
  owner_url: http://github.com/coffeemedsci
  another_url: https://www.youtube.com/watch?v=DN0gAQQ7FAQ